name: Build

on: workflow_dispatch

jobs:
  macos_x86_64:
    strategy:
      matrix:
        os: [macos-13]
        arch: [x86_64]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Build
        run: |
          mkdir build
          mkdir deploy
          cd build
          cmake ..
          make
          cd ..
          cp build/mac/tests/openpnp-capture-test deploy/openpnp-capture-test-${{ matrix.os }}-${{ matrix.arch }}
          cp build/libopenpnp-capture.dylib deploy/libopenpnp-capture-${{ matrix.os }}-${{ matrix.arch }}.dylib

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: openpnp-capture - ${{ runner.os }} ${{ runner.arch }}
          path: |
            deploy/*
            
  macos_arm64: 
    strategy:
      matrix:
        os: [macos-14]
        arch: [arm64]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Build
        run: |
          mkdir build
          mkdir deploy
          cd build
          cmake ..
          make
          cd ..
          cp build/mac/tests/openpnp-capture-test deploy/openpnp-capture-test-${{ matrix.os }}-${{ matrix.arch }}
          cp build/libopenpnp-capture.dylib deploy/libopenpnp-capture-${{ matrix.os }}-${{ matrix.arch }}.dylib

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: openpnp-capture - ${{ runner.os }} ${{ runner.arch }}
          path: |
            deploy/*
            
  windows_x86_64: 
    strategy:
      matrix:
        os: [windows-2022]
        arch: [x86_64]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Visual Studio shell
        uses: egor-tensin/vs-shell@v2

      - name: Build
        run: |
          mkdir build
          mkdir deploy
          cd build
          cmake ..
          cmake --build . --config Release
          cd ..
          cp build/win/tests/Release/openpnp-capture-test.exe deploy/openpnp-capture-test-${{ matrix.os }}-${{ matrix.arch }}.exe
          cp build/Release/openpnp-capture.dll deploy/libopenpnp-capture-${{ matrix.os }}-${{ matrix.arch }}.dll

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: openpnp-capture - ${{ runner.os }} ${{ runner.arch }}
          path: |
            deploy/*
            
  linux_arm64: 
    strategy:
      matrix:
        os: [ubuntu-22.04-arm]
        arch: [arm64]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: "Build"
        run: |
          sudo apt-get update -y && sudo apt-get install -y nasm libgtk-3-dev
          mkdir build
          mkdir deploy
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release cmake ..
          make
          cd ..
          cp build/linux/tests/openpnp-capture-test deploy/openpnp-capture-test-${{ matrix.os }}-${{ matrix.arch }}
          cp build/libopenpnp-capture.so deploy/libopenpnp-capture-${{ matrix.os }}-${{ matrix.arch }}.so

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: openpnp-capture - ${{ runner.os }} ${{ runner.arch }}
          path: |
            deploy/*

  linux_x86_64: 
    strategy:
      matrix:
        os: [ubuntu-22.04]
        arch: [x86_64]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: "Build"
        run: |
          sudo apt-get update -y && sudo apt-get install -y nasm libgtk-3-dev
          mkdir build
          mkdir deploy
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release cmake ..
          make
          cd ..
          cp build/linux/tests/openpnp-capture-test deploy/openpnp-capture-test-${{ matrix.os }}-${{ matrix.arch }}
          cp build/libopenpnp-capture.so deploy/libopenpnp-capture-${{ matrix.os }}-${{ matrix.arch }}.so

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: openpnp-capture - ${{ runner.os }} ${{ runner.arch }}
          path: |
            deploy/*

